apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-config
  namespace: e2e-ms
data:
  DB_HOST: "e2e-ms-db.cknuwegoi2us.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "postgres"