apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-ms
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/itwastheo/E2E-microservice.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: e2e-ms

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true