apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: e2e-ms
spec:
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP