name: Backend Services CI/CD

on:
  push:
    paths:
      - 'authentication/**'
      - 'transaction/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build local Auth for scanning
        uses: docker/build-push-action@v5
        with:
          context: ./authentication
          load: true
          tags: itwastheo/e2e-auth:test-scan

      - name: Scan Auth with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'itwastheo/e2e-auth:test-scan'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Final Push Auth
        uses: docker/build-push-action@v5
        with:
          context: ./authentication
          push: true
          tags: |
            itwastheo/e2e-auth:latest
            itwastheo/e2e-auth:${{ github.sha }}

  build-transaction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build local Transaction for scanning
        uses: docker/build-push-action@v5
        with:
          context: ./transaction
          load: true
          tags: itwastheo/e2e-transaction:test-scan

      - name: Scan Transaction with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'itwastheo/e2e-transaction:test-scan'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Final Push Transaction
        uses: docker/build-push-action@v5
        with:
          context: ./transaction
          push: true
          tags: |
            itwastheo/e2e-transaction:latest
            itwastheo/e2e-transaction:${{ github.sha }}