name: Backend Services CI/CD

on:
  push:
    paths:
      - 'authentication/**'
      - 'transaction/**'
    branches: [ "main" ]

jobs:
  build-authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Authentication
        uses: docker/build-push-action@v5
        with:
          context: ./authentication
          push: true
          tags: |
            itwastheo/e2e-auth:latest
            itwastheo/e2e-auth:${{ github.sha }}

  build-transaction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Transaction
        uses: docker/build-push-action@v5
        with:
          context: ./transaction
          push: true
          tags: |
            itwastheo/e2e-transaction:latest
            itwastheo/e2e-transaction:${{ github.sha }}